### PR TITLE
chore(license): add CC BY-NC 4.0

### PR DESCRIPTION
**Pull request by otkd**
Added license consistent with other Isovalent repos

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for the addition, but since it is text I think it would be better to be under the CC-BY-NC-4.0 like the ebeedex https://github.com/isovalent/ebeedex?tab=License-1-ov-file#readme

**Comment by otkd** [comment]
> Thanks for the addition, but since it is text I think it would be better to be under the CC-BY-NC-4.0 like the ebeedex https://github.com/isovalent/ebeedex?tab=License-1-ov-file#readme

@xmulligan while technically nothing wrong with using Apache 2.0 for non-software purposes I agree CC may be a better option. I have updated the license to CC-BY-4.0 as it is closer to Apache 2.0 and is conformant with the [Open Definition](https://opendefinition.org/licenses/) unlike CC-BY-NC-4.0.

**Comment by xmulligan** [comment]
Thanks for updating. Since there is the Isovalent brand on some of the items, we would prefer it to be NC. Does that make sense?

**Comment by otkd** [comment]
> Thanks for updating. Since there is the Isovalent brand on some of the items, we would prefer it to be NC. Does that make sense?

@xmulligan fair enough, updated to CC BY-NC 4.0

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
Thank you!

**Pull request merged**
